### ISSUE TITLE
Rebase PRs used in suggested programming tasks

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#784]
PRs given as examples in _Developer Guide: Appendix A: Suggested Programming Tasks to Get Started_ need to be rebased to the latest master and ensure they still work as advertised.

**Comment by Zhiyuan-Amos** [comment]
@yamgent can help me verify if the below checkboxes are correct?

- [ ] Command alias #785
- [ ] Remove tag from Person #790
- [ ] Person's `Tag` with color #798 
- [ ] ResultDisplay with error style #799 
- [ ] StatusBar with total Persons #803 
- [ ] Save alternate location #594
- [ ] Remark

**Comment by yamgent** [comment]
> @yamgent can help me verify if the below checkboxes are correct?

Correct so far :+1:

**Comment by Zhiyuan-Amos** [comment]
This issue will be resolved once #789 is merged. However, if we merge #792 (which fixes the bug for undo/redo commands), I think #599 won't be broken, but it'll be buggy (see #792).

**Comment by yamgent** [comment]
> However, if we merge #792 (which fixes the bug for undo/redo commands), I think #599 won't be broken, but it'll be buggy (see #792).

I will take a look at #599 again when that happens then. Don't think I can do anything else to rectify that problem now.

**Comment by Zhiyuan-Amos** [comment]
@yamgent #599 isn't broken but it's buggy (when you undo/redo on a filtered list for `RemarkCommand`). The fix can be found in #792 [3/6] :)

**Comment by Zhiyuan-Amos** [comment]
I've re-run Travis for the PRs mentioned [above](https://github.com/se-edu/addressbook-level4/issues/784#issuecomment-360106921) and they are all passing :)
